name: Python CI

on:
  push:
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install packages with pip
        run: pip install -r requirements.txt
      - name: Lint with pylint
        run: python -m pylint src/
      - name: PEP8 style check with black
        run: python -m black src/
